## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [327]:
import numpy as np
arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', skiprows=1, dtype=np.int32)
print("Первые 5 строк массива:\n",  arr[:5,:])

Первые 5 строк массива:
 [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [328]:
print("Среднее значение времени и количества рецептов:\n", arr[:,1].mean(), arr[:,2].mean())
print("\nМинимальное значение времени и количества рецептов:\n", arr[:,1].min(), arr[:,2].min())
print("\nМаксимальное значение времени и количества рецептов:\n", arr[:,1].max(), arr[:,2].max())
print("\nМедианое значение времени и количества рецептов:\n", np.median(arr[:,1]), np.median(arr[:,2]))

Среднее значение времени и количества рецептов:
 21601.00169 9.05528

Минимальное значение времени и количества рецептов:
 0 1

Максимальное значение времени и количества рецептов:
 2147483647 39

Медианое значение времени и количества рецептов:
 40.0 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [329]:
q075 = np.quantile(arr[:,1], q=0.75, axis=0)
arr[:,1] = arr[:,1].clip(max=q075)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [330]:
count_0_min = np.count_nonzero(arr[:, 1] == 0)

print("Количество рецептов продолжительностью 0 минут:", count_0_min)
arr[arr[:,1] == 0, 1] = 1


Количество рецептов продолжительностью 0 минут: 479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [331]:
print("Количество уникальных рецептов:", len(np.unique(arr, axis=1)))

Количество уникальных рецептов: 100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [333]:
print("Различных количеств ингридиентов:",len(np.unique(arr[:,2])))
print("Различные значения количества ингридиентов:\n", np.unique(arr[:,2]))


Различных количеств ингридиентов: 37
Различные значения количества ингридиентов:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [337]:
version = arr[arr[:,2] <= 5,:].copy()
print("Количество рецептов, состоящих не более чем из 5 ингредиентов:", len(version))

Количество рецептов, состоящих не более чем из 5 ингредиентов: 17262


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [338]:
print("Максимум кол-ва ингредиентов на одну минуту в рецепте:", (arr[:,2] / arr[:, 1]).max())

Максимум кол-ва ингредиентов на одну минуту в рецепте: 24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [340]:
print((arr[arr[:,1].argsort()[::-1]])[:100,2].mean())

9.96


Если под 'топ-100' понимается первые 100 рецептов по порядку следования в датасете с максимальным временем, то среднее количество ингредиентов равно:

In [341]:
print((arr[arr[:,1] == arr[:,1].max()])[:100, 2].mean())

10.03


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [348]:
#rand_rezept = np.random.randint(0, len(arr), size=10) <-- вариант не учитывающий "различные" рецепты

# rand_rezep - вспомогательный массив (первый столбец - случайное число, второй - индекс)
rand_rezept = np.concatenate((np.random.randint(0, 100000, len(arr))[np.newaxis, :].T, np.arange(len(arr))[np.newaxis, :].T), axis=1)

# сортируем и выводим первые 10
print("Информация о 10 различных случайных рецептах:")
print(arr[(rand_rezept[rand_rezept[:, 0].argsort()])[:10, 1]])

# алгоритм гарантирует неповторяющиеся рецепты, сделано без for )

Информация о 10 различных случайных рецептах:
[[461220     20      7]
 [ 33753     15     11]
 [331116     12      4]
 [ 41277     30     10]
 [498714     10      2]
 [408085     60     10]
 [377569     45     12]
 [292834      2      4]
 [391022     20     13]
 [413208     38     15]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [349]:
print("Процент рецептов, кол-во ингредиентов в которых меньше среднего:")
print(len(arr[arr[:, 2] < arr[:, 2].mean()]) * 100 / len(arr), "%")

Процент рецептов, кол-во ингредиентов в которых меньше среднего:
58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [351]:
dop_col = np.arange(len(arr))
dop_col[:] = 0
dop_col[(arr[:,1] <= 20) & (arr[:,2] <= 5)] = 1
dop_col = dop_col[np.newaxis, :]

version2 = np.concatenate((arr, dop_col.T), axis = 1)
print("Версия датасета с дополнительным столбцом:")
print(version2)

Версия датасета с дополнительным столбцом:
[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993     65     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [352]:
print("Процент 'простых' рецептов в датасете:")
print(len(arr[(arr[:,1] <= 20) & (arr[:,2] <= 5)]) / len(arr), "%")

Процент 'простых' рецептов в датасете:
0.09552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [353]:
korotkiy = arr[:, 1] < 10
standartniy = (arr[:, 1] >= 10) & (arr[:, 1] < 20)
dlinniy = arr[:, 1] >= 20

mn_gp = min(len(arr[korotkiy]), len(arr[standartniy]), len(arr[dlinniy]))

mas3D = np.array(((arr[korotkiy])[:mn_gp], (arr[standartniy])[:mn_gp], (arr[dlinniy])[:mn_gp]))
print("Форма полученного массива:", mas3D.shape)
mas3D

Форма полученного массива: (3, 7588, 3)


array([[[ 67660,      5,      6],
        [366174,      7,      9],
        [204134,      5,      3],
        ...,
        [420725,      5,      3],
        [  4747,      1,      9],
        [370915,      5,      4]],

       [[ 94746,     10,      6],
        [ 33941,     18,      9],
        [446597,     15,      5],
        ...,
        [  9831,     15,      7],
        [335859,     12,     14],
        [256812,     10,      3]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [168901,     25,      7],
        [392339,     35,     13],
        [206732,     45,     10]]], dtype=int32)